sub RenameEverything()

 ff4.spells(5).name = white_symbol + ff4.ConvertText("Armor")
 ff4.spells(6).name = white_symbol + ff4.ConvertText("Shell")
 ff4.spells(12).name = white_symbol + ff4.ConvertText("Displ")
 
 ff4.menu_commands(darkwave_command).name = ff4.ConvertText("DWave")
 ff4.menu_commands(recall_command).name = ff4.ConvertText("Recal")
 ff4.menu_commands(salve_command).name = ff4.ConvertText("Salve")
 ff4.menu_commands(pray_command).name = ff4.ConvertText("Pray")
 ff4.menu_commands(charge_command).name = ff4.ConvertText("Chrge")
 ff4.menu_commands(gird_command).name = ff4.ConvertText("Gird")
 ff4.menu_commands(boast_command).name = ff4.ConvertText("Boast")
 ff4.menu_commands(cry_command).name = ff4.ConvertText("Cry")
 ff4.menu_commands(crash_command).name = ff4.ConvertText("Crash")
 ff4.menu_commands(regen_command).name = ff4.ConvertText("Regen") 
 
 ff4.items(70).name = holysword_symbol + ff4.ConvertText("Excalpur")
 ff4.items(176).name = ff4.ConvertText("#BombFrag")
 ff4.items(177).name = ff4.ConvertText("#BombArm")
 ff4.items(178).name = ff4.ConvertText("#S.Wind")
 ff4.items(179).name = ff4.ConvertText("#N.Wind")
 ff4.items(180).name = ff4.ConvertText("#ZeusRage")
 ff4.items(181).name = ff4.ConvertText("#GodsRage")
 ff4.items(182).name = ff4.ConvertText("#Stardust")
 ff4.items(183).name = ff4.ConvertText("#Osmose")
 ff4.items(184).name = ff4.ConvertText("#Drain")
 ff4.items(185).name = potion_symbol + ff4.ConvertText("Baccus")
 ff4.items(186).name = ff4.ConvertText("#Hermes")
 ff4.items(187).name = ff4.ConvertText("#Bronze-H")
 ff4.items(188).name = ff4.ConvertText("#Silver-H")
 ff4.items(189).name = ff4.ConvertText("#Golden-H")
 ff4.items(190).name = ff4.ConvertText("#SilkWeb")
 ff4.items(191).name = mini_symbol + ff4.ConvertText("Scape")
 ff4.items(193).name = ff4.ConvertText("#Ice-Ball")
 ff4.items(195).name = ff4.ConvertText("#LiteVeil")
 ff4.items(196).name = ff4.ConvertText("#Kamikaze")
 ff4.items(197).name = ff4.ConvertText("#MoonVeil")
 ff4.items(198).name = ff4.ConvertText("#MuteBell")
 ff4.items(199).name = ff4.ConvertText("#GaiaDrum")
 ff4.items(201).name = ff4.ConvertText("#Whisker")
 ff4.items(202).name = ff4.ConvertText("#Grimoire")
 ff4.items(203).name = ff4.ConvertText("#Bestiary")
 ff4.items(204).name = potion_symbol + ff4.ConvertText("Alarm")
 ff4.items(205).name = potion_symbol + ff4.ConvertText("Unicorn")
 ff4.items(213).name = potion_symbol + ff4.ConvertText("Soft")
 ff4.items(214).name = potion_symbol + ff4.ConvertText("MaidKiss")
 ff4.items(215).name = potion_symbol + ff4.ConvertText("Mallet")
 ff4.items(216).name = potion_symbol + ff4.ConvertText("DietFood")
 ff4.items(217).name = potion_symbol + ff4.ConvertText("EchoHerb")
 ff4.items(218).name = potion_symbol + ff4.ConvertText("Eyedrop")
 ff4.items(219).name = potion_symbol + ff4.ConvertText("Pure")
 ff4.items(220).name = potion_symbol + ff4.ConvertText("Cross")
 
 ff4.items(222).name = ff4.ConvertText("#Alert")
 ff4.items(223).name = ff4.ConvertText("#G.Apple")
 ff4.items(224).name = ff4.ConvertText("#S.Apple")
 ff4.items(225).name = ff4.ConvertText("#SomaDrop")
 ff4.items(228).name = ff4.ConvertText("#Magazine")
 ff4.items(229).name = ff4.ConvertText("#ExitRock")
 ff4.items(230).name = ff4.ConvertText("#DwarfBun")
 ff4.items(233).name = summon_symbol + ff4.ConvertText("Bird")
 ff4.items(251).name = ff4.ConvertText("#D.Matter")
 ff4.items(252).name = ff4.ConvertText("#KeyItem1")
 ff4.items(253).name = ff4.ConvertText("#KeyItem2")

end sub
