sub RenameEverything()

 ff4.spells(5).name = white_symbol + ff4.ConvertText("Armor")
 ff4.spells(6).name = white_symbol + ff4.ConvertText("Shell")
 ff4.spells(12).name = white_symbol + ff4.ConvertText("Displ")
 
 ff4.menu_commands(darkwave_command).name = ff4.ConvertText("DWave")
 ff4.menu_commands(recall_command).name = ff4.ConvertText("Recal")
 ff4.menu_commands(salve_command).name = ff4.ConvertText("Salve")
 ff4.menu_commands(pray_command).name = ff4.ConvertText("Pray")
 ff4.menu_commands(charge_command).name = ff4.ConvertText("Chrge")
 ff4.menu_commands(gird_command).name = ff4.ConvertText("Gird")
 ff4.menu_commands(boast_command).name = ff4.ConvertText("Boast")
 ff4.menu_commands(cry_command).name = ff4.ConvertText("Cry")
 ff4.menu_commands(crash_command).name = ff4.ConvertText("Crash")
 ff4.menu_commands(regen_command).name = ff4.ConvertText("Regen") 
 
 ff4.items(excalipur_item).name = holysword_symbol + ff4.ConvertText("Excalpur")
 ff4.items(bomb_fragment_item).name = ff4.ConvertText("#BombFrag")
 ff4.items(bomb_arm_item).name = ff4.ConvertText("#BombArm")
 ff4.items(antarctic_wind_item).name = ff4.ConvertText("#S.Wind")
 ff4.items(arctic_wind_item).name = ff4.ConvertText("#N.Wind")
 ff4.items(zeus_rage_item).name = ff4.ConvertText("#ZeusRage")
 ff4.items(gods_rage_item).name = ff4.ConvertText("#GodsRage")
 ff4.items(stardust_item).name = ff4.ConvertText("#Stardust")
 ff4.items(lilith_kiss_item).name = ff4.ConvertText("#Osmose")
 ff4.items(vampire_fang_item).name = ff4.ConvertText("#Drain")
 ff4.items(baccus_wine_item).name = potion_symbol + ff4.ConvertText("Baccus")
 ff4.items(hermes_shoes_item).name = ff4.ConvertText("#Hermes")
 ff4.items(bronze_hourglass_item).name = ff4.ConvertText("#Bronze-H")
 ff4.items(silver_hourglass_item).name = ff4.ConvertText("#Silver-H")
 ff4.items(golden_hourglass_item).name = ff4.ConvertText("#Golden-H")
 ff4.items(silk_web_item).name = ff4.ConvertText("#SilkWeb")
 ff4.items(scape_doll_item).name = mini_symbol + ff4.ConvertText("Scape")
 ff4.items(white_fang_item).name = ff4.ConvertText("#Ice-Ball")
 ff4.items(light_curtain_item).name = ff4.ConvertText("#LiteVeil")
 ff4.items(kamikaze_item).name = ff4.ConvertText("#Kamikaze")
 ff4.items(lunar_curtain_item).name = ff4.ConvertText("#MoonVeil")
 ff4.items(silence_bell_item).name = ff4.ConvertText("#MuteBell")
 ff4.items(earth_drum_item).name = ff4.ConvertText("#GaiaDrum")
 ff4.items(coeurl_whisker_item).name = ff4.ConvertText("#Whisker")
 ff4.items(grimoire_item).name = ff4.ConvertText("#Grimoire")
 ff4.items(bestiary_item).name = ff4.ConvertText("#Bestiary")
 ff4.items(alarm_clock_item).name = potion_symbol + ff4.ConvertText("Alarm")
 ff4.items(unicorn_horn_item).name = potion_symbol + ff4.ConvertText("Unicorn")
 ff4.items(gold_pin_item).name = potion_symbol + ff4.ConvertText("Soft")
 ff4.items(maidens_kiss_item).name = potion_symbol + ff4.ConvertText("MaidKiss")
 ff4.items(mallet_item).name = potion_symbol + ff4.ConvertText("Mallet")
 ff4.items(diet_food_item).name = potion_symbol + ff4.ConvertText("DietFood")
 ff4.items(echo_herb_item).name = potion_symbol + ff4.ConvertText("EchoHerb")
 ff4.items(eyedrop_item).name = potion_symbol + ff4.ConvertText("Eyedrop")
 ff4.items(antidote_item).name = potion_symbol + ff4.ConvertText("Pure")
 ff4.items(cross_item).name = potion_symbol + ff4.ConvertText("Cross")
 
 ff4.items(alert_item).name = ff4.ConvertText("#Alert")
 ff4.items(golden_apple_item).name = ff4.ConvertText("#G.Apple")
 ff4.items(silver_apple_item).name = ff4.ConvertText("#S.Apple")
 ff4.items(soma_drop_item).name = ff4.ConvertText("#SomaDrop")
 ff4.items(magazine_item).name = ff4.ConvertText("#Magazine")
 ff4.items(emergency_exit_item).name = ff4.ConvertText("#ExitRock")
 ff4.items(dwarf_bread_item).name = ff4.ConvertText("#DwarfBun")
 ff4.items(cockatrice_summon_item).name = summon_symbol + ff4.ConvertText("Bird")
 ff4.items(darkmatter_item).name = ff4.ConvertText("#D.Matter")
 ff4.items(unused1_item).name = ff4.ConvertText("#KeyItem1")
 ff4.items(unused2_item).name = ff4.ConvertText("#KeyItem2")
 
 ff4.alert_messages(9).text = ff4.ConvertText("Not enough MP_")
 ff4.alert_messages(15).text = ff4.ConvertText("Not enough potions_")
 ff4.alert_messages(16).text = ff4.ConvertText("Prayer unanswered_")
 ff4.alert_messages(57).text = ff4.ConvertText("Charging_")
 ff4.alert_messages(58).text = ff4.ConvertText("Defense up!")
 ff4.alert_messages(18).text = ff4.ConvertText("Spell power up!")
 ff4.alert_messages(19).text = ff4.ConvertText("Enemies hesitate.")
 ff4.alert_messages(54).text = ff4.ConvertText("Regenerating HP_")

end sub
